/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthenticatedRouteImport } from './routes/app/_authenticated'
import { Route as AppSeamstressRouteImport } from './routes/_app/seamstress'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppAuthenticatedStoreRouteImport } from './routes/app/_authenticated/store'
import { Route as AppAuthenticatedSpecificationsRouteImport } from './routes/app/_authenticated/specifications'
import { Route as AppAuthenticatedRegisterRouteImport } from './routes/app/_authenticated/register'
import { Route as AppAuthenticatedProductsRouteImport } from './routes/app/_authenticated/products'
import { Route as AppAuthenticatedMaterialsRouteImport } from './routes/app/_authenticated/materials'
import { Route as AppAuthenticatedLoginRouteImport } from './routes/app/_authenticated/login'
import { Route as AppAuthenticatedInventoryMovementRouteImport } from './routes/app/_authenticated/inventory-movement'
import { Route as AppAuthenticatedFabricsRouteImport } from './routes/app/_authenticated/fabrics'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRoute = AppAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSeamstressRoute = AppSeamstressRouteImport.update({
  id: '/_app/seamstress',
  path: '/seamstress',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/_app/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedStoreRoute = AppAuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AppAuthenticatedSpecificationsRoute =
  AppAuthenticatedSpecificationsRouteImport.update({
    id: '/specifications',
    path: '/specifications',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedRegisterRoute =
  AppAuthenticatedRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedProductsRoute =
  AppAuthenticatedProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedMaterialsRoute =
  AppAuthenticatedMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedLoginRoute = AppAuthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AppAuthenticatedInventoryMovementRoute =
  AppAuthenticatedInventoryMovementRouteImport.update({
    id: '/inventory-movement',
    path: '/inventory-movement',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedFabricsRoute = AppAuthenticatedFabricsRouteImport.update({
  id: '/fabrics',
  path: '/fabrics',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedRouteWithChildren
  '/login': typeof AppLoginRoute
  '/seamstress': typeof AppSeamstressRoute
  '/app/fabrics': typeof AppAuthenticatedFabricsRoute
  '/app/inventory-movement': typeof AppAuthenticatedInventoryMovementRoute
  '/app/login': typeof AppAuthenticatedLoginRoute
  '/app/materials': typeof AppAuthenticatedMaterialsRoute
  '/app/products': typeof AppAuthenticatedProductsRoute
  '/app/register': typeof AppAuthenticatedRegisterRoute
  '/app/specifications': typeof AppAuthenticatedSpecificationsRoute
  '/app/store': typeof AppAuthenticatedStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedRouteWithChildren
  '/login': typeof AppLoginRoute
  '/seamstress': typeof AppSeamstressRoute
  '/app/fabrics': typeof AppAuthenticatedFabricsRoute
  '/app/inventory-movement': typeof AppAuthenticatedInventoryMovementRoute
  '/app/login': typeof AppAuthenticatedLoginRoute
  '/app/materials': typeof AppAuthenticatedMaterialsRoute
  '/app/products': typeof AppAuthenticatedProductsRoute
  '/app/register': typeof AppAuthenticatedRegisterRoute
  '/app/specifications': typeof AppAuthenticatedSpecificationsRoute
  '/app/store': typeof AppAuthenticatedStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/_app/seamstress': typeof AppSeamstressRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/app/_authenticated/fabrics': typeof AppAuthenticatedFabricsRoute
  '/app/_authenticated/inventory-movement': typeof AppAuthenticatedInventoryMovementRoute
  '/app/_authenticated/login': typeof AppAuthenticatedLoginRoute
  '/app/_authenticated/materials': typeof AppAuthenticatedMaterialsRoute
  '/app/_authenticated/products': typeof AppAuthenticatedProductsRoute
  '/app/_authenticated/register': typeof AppAuthenticatedRegisterRoute
  '/app/_authenticated/specifications': typeof AppAuthenticatedSpecificationsRoute
  '/app/_authenticated/store': typeof AppAuthenticatedStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/seamstress'
    | '/app/fabrics'
    | '/app/inventory-movement'
    | '/app/login'
    | '/app/materials'
    | '/app/products'
    | '/app/register'
    | '/app/specifications'
    | '/app/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/seamstress'
    | '/app/fabrics'
    | '/app/inventory-movement'
    | '/app/login'
    | '/app/materials'
    | '/app/products'
    | '/app/register'
    | '/app/specifications'
    | '/app/store'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/_app/login'
    | '/_app/seamstress'
    | '/app/_authenticated'
    | '/app/_authenticated/fabrics'
    | '/app/_authenticated/inventory-movement'
    | '/app/_authenticated/login'
    | '/app/_authenticated/materials'
    | '/app/_authenticated/products'
    | '/app/_authenticated/register'
    | '/app/_authenticated/specifications'
    | '/app/_authenticated/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppSeamstressRoute: typeof AppSeamstressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/seamstress': {
      id: '/_app/seamstress'
      path: '/seamstress'
      fullPath: '/seamstress'
      preLoaderRoute: typeof AppSeamstressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/store': {
      id: '/app/_authenticated/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppAuthenticatedStoreRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/specifications': {
      id: '/app/_authenticated/specifications'
      path: '/specifications'
      fullPath: '/app/specifications'
      preLoaderRoute: typeof AppAuthenticatedSpecificationsRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/register': {
      id: '/app/_authenticated/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppAuthenticatedRegisterRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/products': {
      id: '/app/_authenticated/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppAuthenticatedProductsRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/materials': {
      id: '/app/_authenticated/materials'
      path: '/materials'
      fullPath: '/app/materials'
      preLoaderRoute: typeof AppAuthenticatedMaterialsRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/login': {
      id: '/app/_authenticated/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppAuthenticatedLoginRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/inventory-movement': {
      id: '/app/_authenticated/inventory-movement'
      path: '/inventory-movement'
      fullPath: '/app/inventory-movement'
      preLoaderRoute: typeof AppAuthenticatedInventoryMovementRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/fabrics': {
      id: '/app/_authenticated/fabrics'
      path: '/fabrics'
      fullPath: '/app/fabrics'
      preLoaderRoute: typeof AppAuthenticatedFabricsRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
  }
}

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedFabricsRoute: typeof AppAuthenticatedFabricsRoute
  AppAuthenticatedInventoryMovementRoute: typeof AppAuthenticatedInventoryMovementRoute
  AppAuthenticatedLoginRoute: typeof AppAuthenticatedLoginRoute
  AppAuthenticatedMaterialsRoute: typeof AppAuthenticatedMaterialsRoute
  AppAuthenticatedProductsRoute: typeof AppAuthenticatedProductsRoute
  AppAuthenticatedRegisterRoute: typeof AppAuthenticatedRegisterRoute
  AppAuthenticatedSpecificationsRoute: typeof AppAuthenticatedSpecificationsRoute
  AppAuthenticatedStoreRoute: typeof AppAuthenticatedStoreRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedFabricsRoute: AppAuthenticatedFabricsRoute,
  AppAuthenticatedInventoryMovementRoute:
    AppAuthenticatedInventoryMovementRoute,
  AppAuthenticatedLoginRoute: AppAuthenticatedLoginRoute,
  AppAuthenticatedMaterialsRoute: AppAuthenticatedMaterialsRoute,
  AppAuthenticatedProductsRoute: AppAuthenticatedProductsRoute,
  AppAuthenticatedRegisterRoute: AppAuthenticatedRegisterRoute,
  AppAuthenticatedSpecificationsRoute: AppAuthenticatedSpecificationsRoute,
  AppAuthenticatedStoreRoute: AppAuthenticatedStoreRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

interface AppRouteRouteChildren {
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppSeamstressRoute: AppSeamstressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
