/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSeamstressRouteImport } from './routes/_app/seamstress'
import { Route as AppauthStoreRouteImport } from './routes/app/(auth)/store'
import { Route as AppauthSpecificationsRouteImport } from './routes/app/(auth)/specifications'
import { Route as AppauthRegisterRouteImport } from './routes/app/(auth)/register'
import { Route as AppauthProductsRouteImport } from './routes/app/(auth)/products'
import { Route as AppauthMaterialsRouteImport } from './routes/app/(auth)/materials'
import { Route as AppauthLoginRouteImport } from './routes/app/(auth)/login'
import { Route as AppauthInventoryMovementRouteImport } from './routes/app/(auth)/inventory-movement'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSeamstressRoute = AppSeamstressRouteImport.update({
  id: '/_app/seamstress',
  path: '/seamstress',
  getParentRoute: () => rootRouteImport,
} as any)
const AppauthStoreRoute = AppauthStoreRouteImport.update({
  id: '/(auth)/store',
  path: '/store',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppauthSpecificationsRoute = AppauthSpecificationsRouteImport.update({
  id: '/(auth)/specifications',
  path: '/specifications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppauthRegisterRoute = AppauthRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppauthProductsRoute = AppauthProductsRouteImport.update({
  id: '/(auth)/products',
  path: '/products',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppauthMaterialsRoute = AppauthMaterialsRouteImport.update({
  id: '/(auth)/materials',
  path: '/materials',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppauthLoginRoute = AppauthLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppauthInventoryMovementRoute =
  AppauthInventoryMovementRouteImport.update({
    id: '/(auth)/inventory-movement',
    path: '/inventory-movement',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/seamstress': typeof AppSeamstressRoute
  '/app/inventory-movement': typeof AppauthInventoryMovementRoute
  '/app/login': typeof AppauthLoginRoute
  '/app/materials': typeof AppauthMaterialsRoute
  '/app/products': typeof AppauthProductsRoute
  '/app/register': typeof AppauthRegisterRoute
  '/app/specifications': typeof AppauthSpecificationsRoute
  '/app/store': typeof AppauthStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/seamstress': typeof AppSeamstressRoute
  '/app/inventory-movement': typeof AppauthInventoryMovementRoute
  '/app/login': typeof AppauthLoginRoute
  '/app/materials': typeof AppauthMaterialsRoute
  '/app/products': typeof AppauthProductsRoute
  '/app/register': typeof AppauthRegisterRoute
  '/app/specifications': typeof AppauthSpecificationsRoute
  '/app/store': typeof AppauthStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/_app/seamstress': typeof AppSeamstressRoute
  '/app/(auth)/inventory-movement': typeof AppauthInventoryMovementRoute
  '/app/(auth)/login': typeof AppauthLoginRoute
  '/app/(auth)/materials': typeof AppauthMaterialsRoute
  '/app/(auth)/products': typeof AppauthProductsRoute
  '/app/(auth)/register': typeof AppauthRegisterRoute
  '/app/(auth)/specifications': typeof AppauthSpecificationsRoute
  '/app/(auth)/store': typeof AppauthStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/seamstress'
    | '/app/inventory-movement'
    | '/app/login'
    | '/app/materials'
    | '/app/products'
    | '/app/register'
    | '/app/specifications'
    | '/app/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/seamstress'
    | '/app/inventory-movement'
    | '/app/login'
    | '/app/materials'
    | '/app/products'
    | '/app/register'
    | '/app/specifications'
    | '/app/store'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/_app/seamstress'
    | '/app/(auth)/inventory-movement'
    | '/app/(auth)/login'
    | '/app/(auth)/materials'
    | '/app/(auth)/products'
    | '/app/(auth)/register'
    | '/app/(auth)/specifications'
    | '/app/(auth)/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AppSeamstressRoute: typeof AppSeamstressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/seamstress': {
      id: '/_app/seamstress'
      path: '/seamstress'
      fullPath: '/seamstress'
      preLoaderRoute: typeof AppSeamstressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/(auth)/store': {
      id: '/app/(auth)/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppauthStoreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(auth)/specifications': {
      id: '/app/(auth)/specifications'
      path: '/specifications'
      fullPath: '/app/specifications'
      preLoaderRoute: typeof AppauthSpecificationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(auth)/register': {
      id: '/app/(auth)/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppauthRegisterRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(auth)/products': {
      id: '/app/(auth)/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppauthProductsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(auth)/materials': {
      id: '/app/(auth)/materials'
      path: '/materials'
      fullPath: '/app/materials'
      preLoaderRoute: typeof AppauthMaterialsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(auth)/login': {
      id: '/app/(auth)/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppauthLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(auth)/inventory-movement': {
      id: '/app/(auth)/inventory-movement'
      path: '/inventory-movement'
      fullPath: '/app/inventory-movement'
      preLoaderRoute: typeof AppauthInventoryMovementRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppauthInventoryMovementRoute: typeof AppauthInventoryMovementRoute
  AppauthLoginRoute: typeof AppauthLoginRoute
  AppauthMaterialsRoute: typeof AppauthMaterialsRoute
  AppauthProductsRoute: typeof AppauthProductsRoute
  AppauthRegisterRoute: typeof AppauthRegisterRoute
  AppauthSpecificationsRoute: typeof AppauthSpecificationsRoute
  AppauthStoreRoute: typeof AppauthStoreRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppauthInventoryMovementRoute: AppauthInventoryMovementRoute,
  AppauthLoginRoute: AppauthLoginRoute,
  AppauthMaterialsRoute: AppauthMaterialsRoute,
  AppauthProductsRoute: AppauthProductsRoute,
  AppauthRegisterRoute: AppauthRegisterRoute,
  AppauthSpecificationsRoute: AppauthSpecificationsRoute,
  AppauthStoreRoute: AppauthStoreRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AppSeamstressRoute: AppSeamstressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
