/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSeamstressRouteImport } from './routes/_authenticated/seamstress'
import { Route as AuthenticatedLoginRouteImport } from './routes/_authenticated/login'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppStoreRouteImport } from './routes/_authenticated/app/store'
import { Route as AuthenticatedAppSpecificationsRouteImport } from './routes/_authenticated/app/specifications'
import { Route as AuthenticatedAppRegisterRouteImport } from './routes/_authenticated/app/register'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app/products'
import { Route as AuthenticatedAppMaterialsRouteImport } from './routes/_authenticated/app/materials'
import { Route as AuthenticatedAppLoginRouteImport } from './routes/_authenticated/app/login'
import { Route as AuthenticatedAppInventoryMovementRouteImport } from './routes/_authenticated/app/inventory-movement'
import { Route as AuthenticatedAppFabricsRouteImport } from './routes/_authenticated/app/fabrics'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeamstressRoute = AuthenticatedSeamstressRouteImport.update({
  id: '/seamstress',
  path: '/seamstress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoginRoute = AuthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppStoreRoute = AuthenticatedAppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSpecificationsRoute =
  AuthenticatedAppSpecificationsRouteImport.update({
    id: '/specifications',
    path: '/specifications',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRegisterRoute =
  AuthenticatedAppRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMaterialsRoute =
  AuthenticatedAppMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppLoginRoute = AuthenticatedAppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppInventoryMovementRoute =
  AuthenticatedAppInventoryMovementRouteImport.update({
    id: '/inventory-movement',
    path: '/inventory-movement',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFabricsRoute = AuthenticatedAppFabricsRouteImport.update({
  id: '/fabrics',
  path: '/fabrics',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/login': typeof AuthenticatedLoginRoute
  '/seamstress': typeof AuthenticatedSeamstressRoute
  '/app/fabrics': typeof AuthenticatedAppFabricsRoute
  '/app/inventory-movement': typeof AuthenticatedAppInventoryMovementRoute
  '/app/login': typeof AuthenticatedAppLoginRoute
  '/app/materials': typeof AuthenticatedAppMaterialsRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/register': typeof AuthenticatedAppRegisterRoute
  '/app/specifications': typeof AuthenticatedAppSpecificationsRoute
  '/app/store': typeof AuthenticatedAppStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/login': typeof AuthenticatedLoginRoute
  '/seamstress': typeof AuthenticatedSeamstressRoute
  '/app/fabrics': typeof AuthenticatedAppFabricsRoute
  '/app/inventory-movement': typeof AuthenticatedAppInventoryMovementRoute
  '/app/login': typeof AuthenticatedAppLoginRoute
  '/app/materials': typeof AuthenticatedAppMaterialsRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/register': typeof AuthenticatedAppRegisterRoute
  '/app/specifications': typeof AuthenticatedAppSpecificationsRoute
  '/app/store': typeof AuthenticatedAppStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/login': typeof AuthenticatedLoginRoute
  '/_authenticated/seamstress': typeof AuthenticatedSeamstressRoute
  '/_authenticated/app/fabrics': typeof AuthenticatedAppFabricsRoute
  '/_authenticated/app/inventory-movement': typeof AuthenticatedAppInventoryMovementRoute
  '/_authenticated/app/login': typeof AuthenticatedAppLoginRoute
  '/_authenticated/app/materials': typeof AuthenticatedAppMaterialsRoute
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/app/register': typeof AuthenticatedAppRegisterRoute
  '/_authenticated/app/specifications': typeof AuthenticatedAppSpecificationsRoute
  '/_authenticated/app/store': typeof AuthenticatedAppStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/seamstress'
    | '/app/fabrics'
    | '/app/inventory-movement'
    | '/app/login'
    | '/app/materials'
    | '/app/products'
    | '/app/register'
    | '/app/specifications'
    | '/app/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/seamstress'
    | '/app/fabrics'
    | '/app/inventory-movement'
    | '/app/login'
    | '/app/materials'
    | '/app/products'
    | '/app/register'
    | '/app/specifications'
    | '/app/store'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/app'
    | '/_authenticated/login'
    | '/_authenticated/seamstress'
    | '/_authenticated/app/fabrics'
    | '/_authenticated/app/inventory-movement'
    | '/_authenticated/app/login'
    | '/_authenticated/app/materials'
    | '/_authenticated/app/products'
    | '/_authenticated/app/register'
    | '/_authenticated/app/specifications'
    | '/_authenticated/app/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seamstress': {
      id: '/_authenticated/seamstress'
      path: '/seamstress'
      fullPath: '/seamstress'
      preLoaderRoute: typeof AuthenticatedSeamstressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/login': {
      id: '/_authenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticatedLoginRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/store': {
      id: '/_authenticated/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AuthenticatedAppStoreRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/specifications': {
      id: '/_authenticated/app/specifications'
      path: '/specifications'
      fullPath: '/app/specifications'
      preLoaderRoute: typeof AuthenticatedAppSpecificationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/register': {
      id: '/_authenticated/app/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AuthenticatedAppRegisterRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/materials': {
      id: '/_authenticated/app/materials'
      path: '/materials'
      fullPath: '/app/materials'
      preLoaderRoute: typeof AuthenticatedAppMaterialsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/login': {
      id: '/_authenticated/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AuthenticatedAppLoginRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/inventory-movement': {
      id: '/_authenticated/app/inventory-movement'
      path: '/inventory-movement'
      fullPath: '/app/inventory-movement'
      preLoaderRoute: typeof AuthenticatedAppInventoryMovementRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/fabrics': {
      id: '/_authenticated/app/fabrics'
      path: '/fabrics'
      fullPath: '/app/fabrics'
      preLoaderRoute: typeof AuthenticatedAppFabricsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppFabricsRoute: typeof AuthenticatedAppFabricsRoute
  AuthenticatedAppInventoryMovementRoute: typeof AuthenticatedAppInventoryMovementRoute
  AuthenticatedAppLoginRoute: typeof AuthenticatedAppLoginRoute
  AuthenticatedAppMaterialsRoute: typeof AuthenticatedAppMaterialsRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppRegisterRoute: typeof AuthenticatedAppRegisterRoute
  AuthenticatedAppSpecificationsRoute: typeof AuthenticatedAppSpecificationsRoute
  AuthenticatedAppStoreRoute: typeof AuthenticatedAppStoreRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppFabricsRoute: AuthenticatedAppFabricsRoute,
  AuthenticatedAppInventoryMovementRoute:
    AuthenticatedAppInventoryMovementRoute,
  AuthenticatedAppLoginRoute: AuthenticatedAppLoginRoute,
  AuthenticatedAppMaterialsRoute: AuthenticatedAppMaterialsRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppRegisterRoute: AuthenticatedAppRegisterRoute,
  AuthenticatedAppSpecificationsRoute: AuthenticatedAppSpecificationsRoute,
  AuthenticatedAppStoreRoute: AuthenticatedAppStoreRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedLoginRoute: typeof AuthenticatedLoginRoute
  AuthenticatedSeamstressRoute: typeof AuthenticatedSeamstressRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedLoginRoute: AuthenticatedLoginRoute,
  AuthenticatedSeamstressRoute: AuthenticatedSeamstressRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
